apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-n6wn
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-n6wn
    app.kubernetes.io/part-of: tkrw-pr714-0075-0014-app
  name: devfile-sample-n6wn
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-n6wn
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-n6wn
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0014-tenant/tkrw-pr714-0075-0014-app/devfile-sample-n6wn@sha256:80bdf747d00744e91d53366cc88343b94d6a36450a5a467701cdb22e15419e82
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
